server:
  port: 8080
debug: true
spring:
  datasource:
    username: short_url
    password: 123456
    url: jdbc:mysql://localhost:3306/short_url?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: short-url-service
customProps:
  ######################################################################################################### url解析设置
  # 是否在没有添加协议时自动添加
  appendProtocolIfEmpty: true
  defaultProtocol: https


  ############################################################################################################# URL检查
  checkUrlMaxLength: true
  maxUrlLength: 255
  # 是否检查协议在允许列表中（如开启此项，尽量将appendProtocolIfEmpty也打开）
  checkProtocols: true
  availableProtocols: http , https , ftp , magnet

  #  是否检查域名是否在禁用名单中
  checkDomain: true
  blockedDomains: s.neko.chat , s.appx.host

  # 是否允许host为ip地址
  allowIpAddress:  true

  # 是否检查域名格式
  checkHostFormat: true
  hostFormatPattern: '^([a-zA-Z0-9]+[.][a-zA-Z0-9]+)+$'

  # 是否检查顶级域名在允许列表中
  checkAvailableTopLevelDomains: true
  availableTopLevelDomains: .com ,.cn ,.chat ,.cc , .net , .edu

  # 是否允许自定义端口号
  allowServerPort: true

  ##################################################################################################### 其他自定义配置
  # 用于解析短域名的url
  #  shortUrlHost: http://s.neko.chat/
  shortUrlHost: http://localhost:8080/
  #网站的icp备案号
  icp: 苏ICP备17002505号-2